### PR TITLE
New branch

### PR DESCRIPTION
**Pull request by kibriyo**
Please review my code

### CODE REVIEW

**Review by OzgurHoruz — CHANGES_REQUESTED** [review]
Please fix typos in the word doesn't and re submit. Thank you!

**Review by OzgurHoruz — APPROVED** [review]

**Review by OzgurHoruz — APPROVED** [review]

**Comment by kibriyo** [comment]
Hello Hello Please check my new code

**Comment by kibriyo** [comment]
Ozgur please check

**Comment by kibriyo** [comment]
Can I merge or you will?

**Review by OzgurHoruz — APPROVED** [review]
Great job kibi!

**Comment by OzgurHoruz** [comment]
> Can I merge or you will?

Yes you can merge kibi

**Comment by kibriyo** [comment]
Perfect done!

**Comment by OzgurHoruz** [comment]
> Perfect done!

Thank you!

**Pull request merged**
